# Generated by Django 4.1.6 on 2023-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsivas', '0002_responsivabackup_detallebackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallebackup',
            options={'permissions': [('supervisor_det', 'Permiso de supervisor en detalles')], 'verbose_name_plural': 'Detalles responsivas backup'},
        ),
        migrations.AlterModelOptions(
            name='responsivabackup',
            options={'permissions': [('supervisor_responsivas', 'Permiso de supervisor en responsivas')], 'verbose_name_plural': 'Responsivas Backup'},
        ),
        migrations.AddField(
            model_name='detallebackup',
            name='en_responsiva',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True),
        ),
    ]
