# Generated by Django 4.1.6 on 2023-02-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre', max_length=100, unique=True)),
                ('funcion', models.CharField(blank=True, help_text='Funcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('NA', 'NA'), ('Interno', 'Interno'), ('Externo', 'Externo')], default='NA', max_length=30)),
                ('interfaz', models.CharField(choices=[('NA', 'NA'), ('SCSI', 'SCSI'), ('IDE', 'IDE'), ('SATA', 'SATA'), ('SSD', 'SSD'), ('USB', 'USB'), ('M-SATA', 'M-SATA'), ('M.2', 'M.2')], default='SATA', max_length=30)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Discos Duros',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre completo', max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Telefono', max_length=20, null=True)),
                ('email', models.CharField(blank=True, help_text='Email', max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, default='default-user.png', null=True, upload_to='empleados/')),
                ('tiene_responsiva', models.CharField(default='No', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('insumo', models.CharField(help_text='Insumo', max_length=50, unique=True)),
                ('modelo', models.CharField(help_text='Modelo', max_length=30)),
                ('serie', models.CharField(help_text='Numero de serie', max_length=30)),
                ('condiciones', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], help_text='Condiciones', max_length=20)),
                ('pantalla', models.CharField(blank=True, choices=[('NA', 'NA'), ('7"', '7"'), ('10.1"', '10.1"'), ('13"', '13"'), ('14"', '14"'), ('15.6"', '15.6"'), ('17"', '17"'), ('19"', '19"'), ('21.5"', '21.5"'), ('23"', '23"'), ('27"', '27"'), ('32"', '32"'), ('40"', '40"'), ('42"', '42"'), ('50"', '50"'), ('55"', '55"'), ('60"', '60"'), ('90"', '90"')], default='NA', max_length=20, null=True)),
                ('caracteristicas', models.CharField(blank=True, default='NA', help_text='Caracteristicas', max_length=300, null=True)),
                ('depto', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, default='default-pc.png', null=True, upload_to='equipos/')),
                ('status', models.CharField(blank=True, choices=[('Asignado', 'Asignado'), ('Libre', 'Libre')], default='Libre', help_text='Status', max_length=20, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(choices=[('NA', 'NA'), ('Intel', 'Intel'), ('AMD', 'AMD')], default='NA', max_length=100)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('generacion', models.IntegerField(blank=True, null=True)),
                ('velocidad', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name_plural': 'Procesadores',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre', max_length=100, unique=True)),
                ('funcion', models.CharField(blank=True, help_text='Funcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=30)),
                ('velocidad', models.IntegerField(blank=True, null=True)),
                ('frecuencia', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Memorias Ram',
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario_edita', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('arquitectura', models.CharField(blank=True, choices=[('NA', 'NA'), ('x86', 'x86'), ('x64', 'x64')], default='NA', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistemas Operativos',
            },
        ),
    ]
