# Generated by Django 4.1.6 on 2023-02-09 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaoperativo',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='ram',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='procesador',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='marca',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.categoria'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='disco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.disco'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='procesador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.procesador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.ram'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.sistemaoperativo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='depto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.departamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.puesto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='disco',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario crea'),
        ),
    ]
