# Generated by Django 4.1.6 on 2023-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_categoria_usuario_edita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='insumo',
            field=models.PositiveIntegerField(help_text='Insumo', unique=True),
        ),
    ]
