# Generated by Django 4.1.6 on 2023-02-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_equipo_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No especifica', 'No especifica')], default='No especifica', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, default='perfil-user.png', null=True, upload_to='empleados/'),
        ),
    ]
