# Generated by Django 4.1.6 on 2023-02-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_empleado_sexo_alter_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='interfaz',
            field=models.CharField(choices=[('-', '-'), ('SCSI', 'SCSI'), ('IDE', 'IDE'), ('SATA', 'SATA'), ('SSD', 'SSD'), ('USB', 'USB'), ('M-SATA', 'M-SATA'), ('M.2', 'M.2')], default='SATA', max_length=30),
        ),
        migrations.AlterField(
            model_name='disco',
            name='tipo',
            field=models.CharField(choices=[('-', '-'), ('Interno', 'Interno'), ('Externo', 'Externo')], default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, default='otro-equipo.jpg', null=True, upload_to='equipos/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='pantalla',
            field=models.CharField(blank=True, choices=[('-', '-'), ('7"', '7"'), ('10.1"', '10.1"'), ('13"', '13"'), ('14"', '14"'), ('15.6"', '15.6"'), ('17"', '17"'), ('19"', '19"'), ('21.5"', '21.5"'), ('23"', '23"'), ('27"', '27"'), ('32"', '32"'), ('40"', '40"'), ('42"', '42"'), ('50"', '50"'), ('55"', '55"'), ('60"', '60"'), ('90"', '90"')], default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='marca',
            field=models.CharField(choices=[('-', '-'), ('Intel', 'Intel'), ('AMD', 'AMD')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemaoperativo',
            name='arquitectura',
            field=models.CharField(blank=True, choices=[('-', '-'), ('x86', 'x86'), ('x64', 'x64')], default='-', max_length=50, null=True),
        ),
    ]
