# Generated by Django 4.1.6 on 2023-02-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_disco_interfaz_alter_disco_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='caracteristicas',
            field=models.CharField(blank=True, default='-', help_text='Caracteristicas', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='depto',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='insumo',
            field=models.PositiveIntegerField(blank=True, help_text='Insumo', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='observaciones',
            field=models.CharField(blank=True, default='-', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='usuario',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
