# Generated by Django 4.1.6 on 2023-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_alter_equipo_caracteristicas_alter_equipo_depto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='insumo',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Insumo', unique=True),
            preserve_default=False,
        ),
    ]
