# Generated by Django 4.1.6 on 2023-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_alter_equipo_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesador',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='velocidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
